### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by allen13** [openshift/jenkins-openshift-login-plugin#3]
I keep getting this during the jenkins boot: 

javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching openshift.default.svc found.

I added openshift.default.svc to my ssl certs and it still doesn't work.

**Comment by gabemontero** [comment]
@allen13 were you running Jenkins inside or outside a OpenShift Pod ?

**Comment by allen13** [comment]
I'm using the official origin jenkins docker from within openshift. I didn't see any options were I could configure SSL.

**Comment by gabemontero** [comment]
@allen13 yeah didn't some polling internally and nobody has seen this .... any chance there is a full java stack trace with that Exception you could post here ?

**Comment by allen13** [comment]
After the above stack trace all I get is:

INFO: OpenShift OAuth: running in OpenShift pod with required OAuth features: false

It might help if i could set the parameters via environment variables or something:

OpenShiftOAuth2SecurityRealm(String serviceAccountDirectory, String serviceAccountName, String serverPrefix, String clientId, String clientSecret, String redirectURL)

Currently everything is being hard set to null:

new OpenShiftOAuth2SecurityRealm(null, null, null, null, null, null)

I realize there might be support for the environment variables already and I might just be missing it in the code.

**Comment by gabemontero** [comment]
`INFO: OpenShift OAuth: running in OpenShift pod with required OAuth features: false` is important here.  It is indicative of the login plugin not being able to retrieve the necessary information from the OpenShift master.  That, along with some use of env vars mounted into the Jenkins pod, is why nulls are OK for the constructor.  It

In the latest versions of the plugin, there is now additional logging around what went precisely wrong.

Which OpenShift Jenkins image and openshift-login plugin are you using?  And which openshift version?  The latest centos images on docker hub already have the latest version of the plugin (The RHEL images won't be updated for a few weeks still).  If you need help determining those versions let me know and I'll spell out the details.  Otherwise, once we get you on the latest version, if there is still an issue, the logs during the Jenkins boot should be more informative.

**Comment by allen13** [comment]
I'll try again once openshift 1.4 comes out. Thanks!

**Comment by bparees** [comment]
@allen13 1.4 is available, have you had a chance to try it?

**Comment by allen13** [comment]
Deploying 1.4 is at the top of our list. I'll be sure to go back and try it.

**Comment by gabemontero** [comment]
An important point I failed to mention back in November (and in fact the README for this plugin is now updated to make this clear).

If you run this plugin against a v1.3.x openshift master, you *MUST* explicitly, properly configure the plugin to operate against the pre-v1.3.x master.  The necessary master-side endpoints that allow the plugin to self-initialize are not available until v1.4 of openshift/origin.

Based on the recent updates today, I think it is now clear the attempt was done against 1.3.x without the explicit configuration.

Correct me if I'm wrong in that interpretation (and reopen this issue accordingly), but based on that, I'm closing this issue out.
